"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { QueryClientProvider, QueryClient } from '@tanstack/react-query'
import Navbar from './components/common/Navbar'
import Footer from './components/common/Footer'
import NavbarMain from './components/common/NavbarMain'
import FooterMain from './components/common/FooterMain'
import { CartProvider } from './context/cartContext'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const queryClient = new QueryClient();
  return (
    <html lang="en">
      <body className={inter.className}>
          <CartProvider>
          <NavbarMain/>
            <QueryClientProvider client={queryClient} >
              {/* <main> */}
                {children}
              {/* </main> */}
              <Toaster />
            </QueryClientProvider>
          <Footer />
          </CartProvider>
        </body>
    </html>
  )
}
